# Global Solution - IOT


##Grupo xcave:

##Pedro Henrico Romania Pires RM: 85439
##Rodrigo André Chiarelli Gonçalves RM: 85716
##Victor Luiz Dias Parisi RM: 84190



## 1.   Importando os dados



In [35]:
import pandas as pd
import numpy as np
from google_drive_downloader import GoogleDriveDownloader as gdd

data_google_id = '1_Q4MnYbqrQcBvIw51eQE4VCA6ugxmA9Q'
gdd.download_file_from_google_drive(file_id=data_google_id, 
                                    dest_path = './dataset_tomate.csv', 
                                    showsize = True)
data=pd.read_csv('dataset_tomate.csv')
data.shape,data.dtypes,data.columns

((132, 23), id              int64
 trat            int64
 NDVI_d28      float64
 SAVI_d28      float64
 GNDVI_d28     float64
 MCARI1_d28    float64
 SR_d28        float64
 NDVI_d01      float64
 SAVI_d01      float64
 GNDVI_d01     float64
 MCARI1_d01    float64
 SR_d01        float64
 NDVI_d04      float64
 SAVI_d04      float64
 GNDVI_d04     float64
 MCARI1_d04    float64
 SR_d04        float64
 NDVI_d08      float64
 SAVI_d08      float64
 GNDVI_d08     float64
 MCARI1_d08    float64
 SR_d08        float64
 Classe          int64
 dtype: object, Index(['id', 'trat', 'NDVI_d28', 'SAVI_d28', 'GNDVI_d28', 'MCARI1_d28',
        'SR_d28', 'NDVI_d01', 'SAVI_d01', 'GNDVI_d01', 'MCARI1_d01', 'SR_d01',
        'NDVI_d04', 'SAVI_d04', 'GNDVI_d04', 'MCARI1_d04', 'SR_d04', 'NDVI_d08',
        'SAVI_d08', 'GNDVI_d08', 'MCARI1_d08', 'SR_d08', 'Classe'],
       dtype='object'))

## 2.  Renomeando as colunas



In [36]:
data.columns=[i for i in 'abcdefghijklmnopqrstuv']+['class']#changing the names of columns

In [37]:
data.head(5)

a    b         c         d  ...         t            u         v  class
0  1  102  0.798284  1.197380  ...  0.636865  13352.81776  5.421333      1
1  2   11  0.806955  1.210392  ...  0.669113  16190.82038  6.491860      0
2  3  103  0.825104  1.237610  ...  0.655206  15313.16198  6.551268      1
3  4  112  0.788884  1.183279  ...  0.640739  16562.17418  6.608121      1
4  5  114  0.764986  1.147432  ...  0.642373  13760.95583  5.665567      1

[5 rows x 23 columns]

In [38]:
data.tail()

a   b         c         d  ...         t            u         v  class
127  128  82  0.750210  1.125268  ...  0.617495  11584.92863  4.928687      1
128  129  81  0.807576  1.211321  ...  0.663861  13727.74708  6.049484      1
129  130  84  0.781299  1.171903  ...  0.626687  13901.73759  5.240016      1
130  131  92  0.760722  1.141037  ...  0.627243  14067.88995  5.514438      1
131  132  93  0.775178  1.162720  ...  0.648120  15801.33386  6.342296      1

[5 rows x 23 columns]

In [39]:
data.columns

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'class'],
      dtype='object')

   ## 4. Normalizando os dados






In [40]:
data.loc[:,'c'] *= 1000000000 
data.loc[:,'d'] *= 1000000000 
data.loc[:,'e'] *= 1000000000 
data.loc[:,'f'] *= 1000000000 
data.loc[:,'g'] *= 1000000000 
data.loc[:,'h'] *= 1000000000 
data.loc[:,'i'] *= 1000000000 
data.loc[:,'j'] *= 1000000000 
data.loc[:,'k'] *= 1000000000 
data.loc[:,'l'] *= 1000000000 
data.loc[:,'m'] *= 1000000000 
data.loc[:,'n'] *= 1000000000 
data.loc[:,'o'] *= 1000000000 
data.loc[:,'p'] *= 1000000000 
data.loc[:,'q'] *= 1000000000 
data.loc[:,'r'] *= 1000000000 
data.loc[:,'s'] *= 1000000000 
data.loc[:,'t'] *= 1000000000 
data.loc[:,'u'] *= 1000000000 
data.loc[:,'v'] *= 1000000000 
data


a    b            c  ...             u             v  class
0      1  102  798284346.0  ...  1.335282e+13  5.421333e+09      1
1      2   11  806954675.0  ...  1.619082e+13  6.491860e+09      0
2      3  103  825103716.0  ...  1.531316e+13  6.551268e+09      1
3      4  112  788884018.0  ...  1.656217e+13  6.608121e+09      1
4      5  114  764985935.0  ...  1.376096e+13  5.665567e+09      1
..   ...  ...          ...  ...           ...           ...    ...
127  128   82  750210172.0  ...  1.158493e+13  4.928687e+09      1
128  129   81  807575817.0  ...  1.372775e+13  6.049484e+09      1
129  130   84  781298705.0  ...  1.390174e+13  5.240016e+09      1
130  131   92  760722281.0  ...  1.406789e+13  5.514438e+09      1
131  132   93  775177889.0  ...  1.580133e+13  6.342296e+09      1

[132 rows x 23 columns]



## 5.   Convertendo os tipos




In [41]:
data['b']=data['b'].astype(dtype='i')
data['c']=data['c'].astype(dtype='i')
data['e']=data['e'].astype(dtype='i')
data['d']=data['d'].astype(dtype='i')
data['f']=data['f'].astype(dtype='i')
data['g']=data['g'].astype(dtype='i')
data['h']=data['h'].astype(dtype='i')
data['i']=data['i'].astype(dtype='i')
data['j']=data['j'].astype(dtype='i')
data['k']=data['k'].astype(dtype='i')
data['l']=data['l'].astype(dtype='i')
data['m']=data['m'].astype(dtype='i')
data['n']=data['n'].astype(dtype='i')
data['o']=data['o'].astype(dtype='i')
data['p']=data['p'].astype(dtype='i')
data['q']=data['q'].astype(dtype='i')
data['r']=data['r'].astype(dtype='i')
data['s']=data['s'].astype(dtype='i')
data['t']=data['t'].astype(dtype='i')
data['u']=data['u'].astype(dtype='i')
data['v']=data['v'].astype(dtype='i')

In [42]:
data.head(5)

a    b          c           d  ...          t           u           v  class
0  1  102  798284346  1197380165  ...  636864799 -2147483648 -2147483648      1
1  2   11  806954675  1210392005  ...  669112589 -2147483648 -2147483648      0
2  3  103  825103716  1237610132  ...  655206208 -2147483648 -2147483648      1
3  4  112  788884018  1183279017  ...  640739202 -2147483648 -2147483648      1
4  5  114  764985935  1147431616  ...  642372545 -2147483648 -2147483648      1

[5 rows x 23 columns]

##3.   Removendo as colunas

In [43]:
data.drop(['a'],axis=1,inplace=True)
data.drop(['f'],axis=1,inplace=True)
data.drop(['k'],axis=1,inplace=True)
data.drop(['l'],axis=1,inplace=True)
data.drop(['p'],axis=1,inplace=True)
data.drop(['q'],axis=1,inplace=True)
data.drop(['u'],axis=1,inplace=True)
data.drop(['v'],axis=1,inplace=True)

In [44]:
newdata=data.values.tolist()
newdata=np.array(newdata)
newdata

array([[       102,  798284346, 1197380165, ..., 1026146315,  636864799,
                 1],
       [        11,  806954675, 1210392005, ..., 1088239800,  669112589,
                 0],
       [       103,  825103716, 1237610132, ..., 1092214401,  655206208,
                 1],
       ...,
       [        84,  781298705, 1171903300, ..., 1009325603,  626687278,
                 1],
       [        92,  760722281, 1141036601, ..., 1027701091,  627243268,
                 1],
       [        93,  775177889, 1162720281, ..., 1072979345,  648119889,
                 1]])

In [45]:
newclass=data['class']


In [46]:
len(newdata),len(newclass)

(132, 132)



## 6.  Criando dados de treinamento e de teste




In [47]:
train=newdata[:int(len(newdata)*0.7)]
test=newdata[int(len(newdata)*0.3): ]

In [48]:
train[0]

array([        102,   798284346,  1197380165,   692651956, -2147483648,
         729766917,  1094619847,   698726412,   713178955,  1069718399,
         662424602,   684125239,  1026146315,   636864799,           1])

In [49]:
train_set={0:[],1:[]}
test_set={0:[],1:[]}
train_set

{0: [], 1: []}

In [50]:
for i in train:
    train_set[i[-1]].append(i[:-1])
train_set

{0: [array([         11,   806954675,  1210392005,   705323218, -2147483648,
           774359038,  1161513501,   717366713,   777758122,  1166604163,
           680268759,   725520577,  1088239800,   669112589]),
  array([         13,   806006126,  1208966061,   698521522, -2147483648,
           776762107,  1165121191,   712256085,   757990792,  1136946885,
           663469302,   721818860,  1082688193,   654506147]),
  array([         14,   778407902,  1167566370,   674224062, -2147483648,
           755313395,  1132946923,   697299857,   731637782,  1097414594,
           648051446,   723708922,  1085521285,   659776335]),
  array([        161,   772798694,  1159150797,   667518137, -2147483648,
           739449301,  1109145089,   686722647,   737798831,  1106649107,
           669850568,   772525867,  1158744760,   702535446]),
  array([        162,   788265898,  1182351331,   682605670, -2147483648,
           773298329,  1159920277,   712432850,   745386744,  1118028388,
     

In [51]:
for i in test:
    test_set[i[-1]].append(i[:-1])
test_set

{0: [array([        173,   815877879,  1223772620,   690969390, -2147483648,
           803321223,  1204958423,   727245721,   783096022,  1174595074,
           716055763,   806537589,  1209766660,   727334952]),
  array([        191,   659674091,   989466709,   570998835, -2147483648,
           666397235,   999568894,   618320762,   670622953,  1005890443,
           594110956,   678982168,  1018432607,   612002396]),
  array([        194,   699347110,  1048973395,   592230835, -2147483648,
           691883654,  1037802490,   623635980,   683078924,  1024571447,
           603176142,   714000087,  1070959784,   632550498]),
  array([        192,   701884761,  1052777775,   578258242, -2147483648,
           715134376,  1072675294,   622891525,   715288104,  1072887466,
           600716140,   728208513,  1092274129,   627083795]),
  array([         21,   777937190,  1166863212,   670603887, -2147483648,
           765304265,  1147932994,   699105390,   777302417,  1165920939,
     

***KNN***

In [52]:
import numpy as np
from collections import Counter
def knn(data,prd):
    dist=[]
    for grp in data:
        for pt in data[grp]:
            dist.append((np.linalg.norm(np.array(pt)-np.array(prd)),grp))
            votes= sorted(dist)[:3]
            print(votes)
            votes=[i[1] for i in votes]
    
    return Counter(votes).most_common(1)[0][0]
      

***Rodando o teste***

In [53]:
c=0
t=0
for gr in test_set:
    for p in test_set[gr]:
        if gr==knn(train_set,p):
            c+=1
        t+=1   

A saída de streaming foi truncada nas últimas 5000 linhas.
[(40914256.24438138, 1), (48979657.72971536, 1), (53506597.822108, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657.72971536, 1)]
[(0.0, 1), (40914256.24438138, 1), (48979657

***Acerto***

In [54]:
c/t

0.9354838709677419